- RandomChoiceApp.xcodeproj/project.pbxproj
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/View/Base.lproj/Main.storyboard
- RandomChoiceApp/View/ListPageTableViewCell.swift
- RandomChoiceApp/View/ListPageTableViewCell.xib
> 一覧画面のUIを作成

- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/View/Base.lproj/Main.storyboard
- RandomChoiceApp/View/Cells/SignupCategoryTableViewCell.swift
> キーボードが下がるように実装

- RandomChoiceApp.xcodeproj/project.pbxproj
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/View/Base.lproj/Main.storyboard
- RandomChoiceApp/View/Cells/RandomChoiceButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/RandomChoiceButtonTableViewCell.xib
- RandomChoiceApp/View/Cells/SelectConditionsTableViewCell.swift
- RandomChoiceApp/View/Cells/SelectConditionsTableViewCell.xib
セルの高さは固定になっていますが、相談後変更します
スクロールもまだ可能のままです
レビューお願いします！
> ランダムチョイスページのUI作成

- RandomChoiceApp.xcodeproj/project.pbxproj
> BundleIDの修正

- RandomChoiceApp.xcodeproj/project.pbxproj
- RandomChoiceApp/Controller/AppDelegate.swift
- RandomChoiceApp/Model/AnonymousLoginModel.swift
匿名ログインのリファクタリング
匿名ログインのリファクタリング
変わらず匿名ログインができているか？
OK
> 匿名ログインのリファクタリング

- RandomChoiceApp/View/Base.lproj/Main.storyboard
**概要**
・新規登録ページのtableViewCellを一つ削除 (storyboard上)
> 新規登録ページのセルを一つ削除

- RandomChoiceApp/Model/StoreDataCrudModel.swift
**clone コマンド**
git clone -b feature/fix-uid git@github.com:HaraFuchi/RandomChoiceApp.git
**Trello**
匿名ログインが新たにできない
**概要**
・新規端末で匿名ログインした際クラッシュするのを防ぐ
・強制アンラップを修正
新規端末で問題なくログインできるかどうか
実機build/期待通りの挙動をするか
OK (新規の実機ビルドはしていない)
> 新規端末で匿名ログインした際クラッシュするのを防ぐ

- RandomChoiceApp.xcodeproj/project.pbxproj
- RandomChoiceApp/Info.plist
**概要**
バージョンを1.1.0に更新しました。
以下の箇所を変更
・TARGETSのGeneralのVersion
・info.plist
> バージョンを1.1.0に上げる

- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/Model/StoreDataCrudModel.swift
- RandomChoiceApp/View/Cells/CommonActionButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/CommonActionButtonTableViewCell.xib
- RandomChoiceApp/View/Cells/ListPageTableViewCell.swift
- RandomChoiceApp/View/Cells/ListPageTableViewCell.xib
- RandomChoiceApp/View/Cells/SignupCategoryTableViewCell.swift
git clone -b feature/fix-text-and-typo git@github.com:HaraFuchi/RandomChoiceApp.git
タイポ修正
- タイポチェックツールにより明るみになったタイポの修正
- 一部文言修正
タイポではない赤線を無視する場合(uidなど)
https://qiita.com/am10/items/2cf5576d7b36b4097cac#ignorelearn
OK
なし
なし
> タイポ修正 / 文言修正

- RandomChoiceApp.xcodeproj/project.pbxproj
- RandomChoiceTests/Info.plist
- RandomChoiceTests/RandomChoiceTests.swift
- RandomChoiceUITests/Info.plist
- RandomChoiceUITests/RandomChoiceUITests.swift
git clone -b feature/add-test-files git@github.com:HaraFuchi/RandomChoiceApp.git
UnitTest/UITest追加
テスト関連のファイルを作成
特になし
チェック不要
ファイルを追加しただけなので、追加をしなくて大丈夫です。
> テスト関連のファイル追加

- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/LiteralConstraints.swift
git clone -b feature/fix-conflict-error git@github.com:HaraFuchi/RandomChoiceApp.git
コンフリクト解消によるエラー解消
- コンフリクトにより出たbuildエラーの解消
- 一部リファクタリング
- README削除
buildが問題なくできるかどうか？
OK
> コンフリクト解消により発生したbuildエラーの解消 / リファクタリング

- RandomChoiceApp.xcodeproj/project.pbxproj
- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/View/Base.lproj/Main.storyboard
- RandomChoiceApp/View/Cells/ListPageTableViewCell.swift
- RandomChoiceApp/View/Cells/ListPageTableViewCell.xib
**clone コマンド**
git clone -b add-UI-EditPage git@github.com:HaraFuchi/RandomChoiceApp.git
**Trello**
該当のTrelloのチケットの名称を共有
**概要**
編集ページのUI作成
・お店一覧から編集ページに遷移できるか
・編集ページのUIはどうか
**実機build/期待通りの挙動をするか**
OK
**補足**
編集ページのキャンセルボタンを押しても戻る機能はまだ実装していません。
> 編集ページのUIを作成

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/LiteralConstraints.swift
- RandomChoiceApp/View/Cells/CommonActionButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/CommonActionButtonTableViewCell.xib
**clone コマンド**
git clone -b feature/fix-conflict git@github.com:HaraFuchi/RandomChoiceApp.git
**Trello**
ボタンのリテラル / 登録ボタンの文言をコードで書く
**概要**
・リネームによって起きたエラーを解消
・登録ボタンと編集ボタンのハードコーディング
・ビルドエラーは起きないか
・ボタンの文言は正確に表示されるかどうか
**実機build/期待通りの挙動をするか**
OK
> コンフリクト解消によるエラーを解消

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/Model/StoreDataCrudModel.swift
git clone -b feature/fix-viewDidLoad git@github.com:HaraFuchi/RandomChoiceApp.git
func viewDidLoad() リファクタリング
- ViewDidLoad内に書かれたTableView関連を1つのメソッドにまとめる
- 冗長なメソッドを分ける
問題なく動作をするか
OK
> ライフサイクル関係のリファクタリング

- RandomChoiceApp/Controller/SignupViewController.swift
**Trello**
登録画面のヘッダー修正
**概要**
・新規登録画面のナビゲーションバーのレイアウトを修正
・ステイタスバーまで広げる
> 登録画面のヘッダー修正

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/View/Base.lproj/Main.storyboard
**clone コマンド**
git clone -b feature/add-AutoLayout-Edit git@github.com:HaraFuchi/RandomChoiceApp.git
**Trello**
編集ページのオートレイアウト
**概要**
・編集画面のオートレイアウト
・SafeAreaの背景色変更 (グレー)
・オートレイアウトの制約は正しいか
実機build/期待通りの挙動をするか
OK
> 編集画面のオートレイアウト

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/Model/StoreDataCrudModel.swift
- RandomChoiceApp/View/Cells/CommonActionButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/ListPageTableViewCell.swift
- RandomChoiceApp/View/Cells/RandomChoiceButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/SignupCategoryTableViewCell.swift
git clone -b feature/fix-extention-and-tableView git@github.com:HaraFuchi/RandomChoiceApp.git
- MとVのメソッドのCと同じようにリファクタリングして統一感を出す
- tableViewのDelegate不要な部分は消去する
コードのリファクタリング
アプリが問題なく動くか
OK
> extensionとtableViewのリファクタリング

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/View/Cells/ListPageTableViewCell.swift
git clone -b feature/add-TF-text git@github.com:HaraFuchi/RandomChoiceApp.git
更新画面のTFにテキストを反映させる
更新画面のTFにテキストを反映させる
更新画面のTFにテキストを反映させることができるか
命名が適切かどうか?
OK
> 更新画面のTFにテキストを反映させる

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/LiteralConstraints.swift
git clone -b feature/fix-hard-coding git@github.com:HaraFuchi/RandomChoiceApp.git
Cellなど文言のハードコーディング修正
ハードコーディング 実施
- 命名が適切か？
- ちゃんとアプリが動くか？
OK
ミスったら致命的なので、必ず動作確認お願いします！
> ハードコーディング修正

- RandomChoiceApp/Controller/ListViewController.swift
git clone -b feature/fix-bug-TF-value git@github.com:HaraFuchi/RandomChoiceApp.git
コンフリクトを解消すると値がうまく反映されない
コンフリクト解消によって、更新画面の値が正しく反映されないため修正
更新画面で値が正しく反映されるかどうか？
OK
> 更新画面の値が正しく反映されないため修正

- RandomChoiceApp/Controller/AppDelegate.swift
**clone コマンド**
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b  feature/fix-launchingTime
**Trello**
起動画面の表示時間調整
**概要**
・起動画面の表示時間を長くする(0.5秒)
・起動画面の表示時間が一定になっているか
**参考URL**
https://qiita.com/e9d26/items/26fab0bed16aec69d176
**実機build/期待通りの挙動をするか**
OK
**レビュー依頼**
@yamataku29
@fuchi0741
> 起動画面の表示時間を変更

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/LiteralConstraints.swift
- RandomChoiceApp/Model/StoreDataCrudModel.swift
- RandomChoiceApp/View/Cells/CommonActionButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/RandomChoiceButtonTableViewCell.swift
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b fix/name
命名が適切かを話す会
命名のリネームをする
- 命名が適切かどうか ?
- 問題なく動作するか?
OK
> 命名した箇所のリネーム

- RandomChoiceApp/Controller/AppDelegate.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b refactor/add-access-modifier-controller
controllerにアクセス修飾子を追加して保守性と可読性を高める
- controllerのプロパティにアクセス修飾子を追加
→保守性と可読性の向上を期待
- 特になし
OK
@AyanoHara  レビューお願いしますーー！
> コントローラーにアクセス修飾子を追加

- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b remove/cancel-button-hidden
キャンセルボタンを隠す仕様を削除
#54 で**実施した登録0件の場合は登録画面のキャンセルボタンを隠す**仕様を削除
消しそびれている部分はあるか
特になし
OK
@AyanoHara  
レビューお願いしますー！
> キャンセルボタンを隠す仕様を削除

- RandomChoiceApp/Controller/EditViewController.swift
- RandomChoiceApp/Controller/ListViewController.swift
- RandomChoiceApp/Controller/RandomChoiceViewController.swift
- RandomChoiceApp/Controller/SignupViewController.swift
- RandomChoiceApp/View/Cells/CommonActionButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/ListPageTableViewCell.swift
- RandomChoiceApp/View/Cells/RandomChoiceButtonTableViewCell.swift
- RandomChoiceApp/View/Cells/SignupCategoryTableViewCell.swift
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b feature/add-private-access-view
Viewにアクセス修飾子を追加して保守性と可読性を高める
Viewにアクセス修飾子を追加して保守性と可読性を高める
より適切な命名はあるか？
OK
@AyanoHara  
レビューお願いしますー！
> Viewファイルにアクセス修飾子を追加
